
-- Criação da tabela COMPOSICAO_FAMILIAR_BPC_2025 com base na lógica discutida
CREATE MULTISET TABLE DL_DBAP.COMPOSICAO_FAMILIAR_BPC_2025, NO BEFORE JOURNAL, NO AFTER JOURNAL, CHECKSUM = DEFAULT, DEFAULT MERGEBLOCKRATIO,
BLOCKCOMPRESSION=ALWAYS, BLOCKCOMPRESSIONLEVEL=9 AS (
WITH FAMILIA AS (
    SELECT
        A.CO_FAMILIA,
        A.NU_CPF_PESSOA,
        A.NO_PESSOA,
        A.CO_SEQ_FAMILIA,
        A.CO_MUNICIPIO_IBGE,
        A.CO_UF,
        A.CO_NIS_PESSOA,
        A.DT_NASCIMENTO,
        A.CO_SEXO,
        A.CO_GRAU_PARENTESCO,
        A.CO_SITUACAO_MEMBRO,
        A.CO_NB,
        ROW_NUMBER() OVER (PARTITION BY A.CO_NB ORDER BY CASE 
            WHEN A.CO_GRAU_PARENTESCO = 1 THEN 1
            WHEN A.CO_GRAU_PARENTESCO = 3 THEN 2
            ELSE 3
        END) AS ORDEM
    FROM P_DBAP_ACC.VW_MACICA_202503_CADUN_202503 A
    WHERE A.CO_NB IS NOT NULL
)
SELECT
    F.CO_NB,
    F.CO_FAMILIA,
    F.NU_CPF_PESSOA,
    F.NO_PESSOA,
    F.CO_SEQ_FAMILIA,
    F.CO_MUNICIPIO_IBGE,
    F.CO_UF,
    F.CO_NIS_PESSOA,
    F.DT_NASCIMENTO,
    F.CO_SEXO,
    F.CO_GRAU_PARENTESCO,
    F.CO_SITUACAO_MEMBRO,
    CASE
        WHEN F.ORDEM = 1 THEN 'REFERENCIA'
        ELSE 'FAMILIAR'
    END AS TIPO_VINCULO
FROM FAMILIA F
) WITH DATA PRIMARY INDEX (CO_NB);
